apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xr32ai0af-nodejs 
  janus-idp.io/tekton: xr32ai0af-nodejs
  backstage.io/kubernetes-id: xr32ai0af-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xr32ai0af-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml